### ISSUE TITLE
No main.h file

### ISSUE THREAD

**Issue by sourishss** [fma23/Digital-Peak-Current-Mode-DC-DC-Buck-Converter#1]
Hi, 

Thanks for the detailed explanation. I imported your folder in my CCS but it shows the error "missing main.h" file which is actually not uploaded in your git hub attachment folder

**Comment by fma23** [comment]
I will add the missing file or upload the entire project sometime tonight. Keep an eye

**Comment by fma23** [comment]
The main file is there. It is named: buck_main.c 


Hope this helps!

**Comment by sourishss** [comment]
Hi Farid,

Hope you are doing well.

Yes main.c file is there, I meant that main.h file is not there.

Thanks for confirming that you will upload the full project. That helps a
lot.

Thanks and Regards,
Sourish

**Comment by sourishss** [comment]
Hi Farid,

Hope you are doing well. 

As mentioned by you in the email to reply back here in the website comment box. I will explain the issue in detail. I imported the whole github folder in CCS (after extraction from zip folder) and clicked built. The error that I got was missing "main.h" file. I looked into the "main.c" file which now I believe you have renamed as "buck_main.c" file and saw that it has a statement  #include "main.h" in line 16. However, the github folder does not have this "main.h" file.

This is giving an error after I built this folder in CCS. I hope I could explain it to you.

I am trying to learn coding in TI controller F28069 recently, I haven’t had much exposure to embedded programming. 
Finally what I am required in my PhD work (in North Carolina State University) is to work on Resonant Converters and as such I felt a simple buck converter will be a good place to start with.

Let me know if you need any further information from me.

Thank you for your help.

Regards,
Sourish

**Comment by fma23** [comment]
I will either send you the whole project or give you access to it on my drop box once I get home. All the bests!

**Comment by sourishss** [comment]
Thank you Farid.

**Comment by fma23** [comment]
I created another repo with the entire project at: 
https://github.com/fma23/Buck-Converter-Peak-Current-Control-Mode-Theory

**Comment by fma23** [comment]
Did you manage to clone my TI new repo, and compile the project? Hope you did

**Comment by sourishss** [comment]
Hi Farid,

I am actually trying to build it since yesterday but it still has some issues. I believe it is because of the fact that my CCS v10 is different than yours.
I wanted to tell you but it feels to bad to disturb someone often. 

Since you asked I have attached a file which shows the error that I am getting and how I built in my CCS. If you see any mistake then I will be glad if you can point me out.

If you want I can also give you my CCS imported file. I had to make some changes in the include and linker files in the properties due to the use of CCS v10.

Regards,
Sourish

[CCS_imported_Farid_Boosterpack.docx](https://github.com/fma23/Digital-Peak-Current-Mode-DC-DC-Buck-Converter/files/5721974/CCS_imported_Farid_Boosterpack.docx)

**Comment by fma23** [comment]
Looks like the issue you have is a linking problem. I suggest the best way is not to create a new project and add my files to it, but rather import my project into your code composer ide. There is an option on the top bar menu for that. This way it should run just fine. Another advice is not to change the linker at all. I remember I had had time to make it run from the flash.

**Comment by sourishss** [comment]
Hi Farid,

Yes that is what I did first time. I imported your project through CCS -> Project -> Import CCS Project. However, as I have again attached a file I got several errors. Ultimately after removing all of those I reached the same situation where only the linker issue persists. 

[CCS_imported_Farid_Boosterpack - rev2.docx](https://github.com/fma23/Digital-Peak-Current-Mode-DC-DC-Buck-Converter/files/5722163/CCS_imported_Farid_Boosterpack.-.rev2.docx)

**Comment by sourishss** [comment]
Hi Farid,

I have some questions on your code. I would appreciate if you can spend some time in clearing them for me. I am a bit poor in reading codes and thus many of these questions might simply be too naïve, my apologies if that is so.

1 - In your HW_Configuration.c file you have written the following :
Line # 21
Comp2Regs.DACVAL.bit.DACVAL = 1280>>5; 

Where does 1280 come from and what does 1280>>5 mean ?

2 - In your HW_Configuration.c file you have written the following :
    Line # 64 to 71
EPwm1Regs.AQCTLA.bit.ZRO = AQ_SET;          /* Set PWM1A on Zero */
   EPwm1Regs.AQCTLA.bit.CAU = AQ_CLEAR;        /* Clear PWM1A on match on count A up */
   EPwm1Regs.AQCTLB.bit.ZRO = AQ_SET;          /* Set PWM1B on Zero */
   EPwm1Regs.AQCTLB.bit.CBU = AQ_CLEAR;        /* Clear PWM1B on match on count B up */

   EPwm1Regs.CMPB = DutyCycle_PWMB;                       /* Set compare B value */
   EPwm1Regs.CMPA.half.CMPA = DutyCycle_PWMA;             /* Set compare A value */
   EPwm1Regs.TBPRD = PERIOD;                   /* Set period for ePWM1 */

I am not able to understand why do we need both CMPA  and CMPB since both of these are related to the Comparator action , and why are both starting at the same time ? I am just confused as to why does this comparator need the EPWM1 signals.

3- In your explanation in the website you have written that CLA Task 1 is used to trigger ADC Channel A3. However, in HW_Configuration.c the ADC which is called for to trigger EMPW1 is on ADCINB0. Is it a typing mistake in your website or am I getting something wrong ?

4- It is not clear to me which ADC pins are you using to take the voltage and current sensed signal. I could not find it in your code.

5 - In Buck_main.c file you have written the following : 
   Line # 114 to 121

Comparator_Config();
    GpioDataRegs.GPASET.bit.GPIO10=1;   //active load for buckdevboard
    InitCpuTimers();
    //configure timer1;Frequency in MHz, period in Useconds
    ConfigCpuTimer(&CpuTimer1,90,1000000);
    // To ensure precise timing, use write-only instructions to write to the entire register. Therefore, if any
    // of the configuration bits are changed in ConfigCpuTimer and InitCpuTimers (in F2806x_CpuTimers.h), the
    // below settings must also be updated.
    CpuTimer1Regs.TCR.all = 0x4000; // Use write-only instruction to set TSS bit = 0

I believe these statements indicate the turning on of the active load after the time set in the ConfigCpuTimer statement, am I correct ?

Thanks and Regards,
Sourish

**Comment by sourishss** [comment]
Hi Farid,

Can you please reply back to my doubts. It would be a lot of help. 

Thanks and Regards,
Sourish

**Comment by fma23** [comment]
Hi Sourish, 

I am sorry I am busy these days, and I could not get back to you earlier. I believe before you jumping to my code you need to run through the references I cited  on the webpage related to the buck converter. There is an app note that describes how the peak current mode control theory is implemented. 

once you nail down the implementation, then take the example code that comes with C2000 package for the dev board I used, and review that code and make sure it makes sense to you. Then keep that working directory as it is and add my files to it and remove the demo files. There is also  forum on TI website and I found it very useful when I was working with TI MCUs.

back to your questions: 
1. Comp2Regs.DACVAL.bit.DACVAL: this register sets the tripping voltage for the comparator. You know at what analog voltage you want the PWM to trip. This is a design related parameter.
2. I used only one compartor; but I used two PWM channels per PWM GPIO pin: one PWM channels controls the power MOSFET( the switch) and the other PWM is used to set the start of conversion for the ADC ( meaning that at the falling edge of this PWM, a start of conversion interrupt is generated for the ADC so that it samples the output voltage). then, the CLA get an interrupt at the end of conversion so that PID value is calculated and converted into a DC value that I send to the DAC. remember also that the DAC DC level is decremented at every clock cycle.( this is needed when duty cycle is more than 50 percent)
3. CLA does not trigger any thing. CLA task is triggered by the ADC EOC ( end of conversion) so that the PID value is calculated and converted into a DC value.
4.  I used a timer for soft start. I did not want to force the system to give high current immediately.  This is a design choice.

I hope this helps!

**Comment by fma23** [comment]
any future questions, please post on the web page so that other readers might benefit or even answer some of your questions.
Thanks!

**Comment by sourishss** [comment]
Hi Farid
Understood. I will refer to the other references you mentioned and come back to you if I still have any doubts in your code

**Comment by sourishss** [comment]
Hi Farid,

 I would like to have a small help from you. I understood most of the code. But, there are just few things that I am unable to understand.

1 - As you can see in the attached file there for Digital Power BoosterPack board that H2[4] pin is used for ILFB feedback current. I don't see anywhere in the code which says to which pin in the microcontroller should this be connected to. Since I believe this is the sensed current which will be compared to the slope compensated controller value for the tripping action.

2 - I connected the H2[7] pin on the BoosterPack board (attached image) to the ADCINA3 pin as per your code, but this pin ADCINA3 is supposed to be sampled based on the interrupt generated every cycle by EPWM1B. So should there be any connection externally made between ADCINA3 pin and GPIO1 ?

3 -  If I want to do just 2P2Z Compensator to operate (not PID) then how do I do that ? I was wondering if due to multiple compensators taking action at the same time is what leads to not operation of the board. Do I have to choose COMPENSATOR = 1 somewhere ? Does BuckControl_Ref get its value from Cmpns2_Coef ? then where does Cmpns2_Coef get its value from ?

As a matter of fact I am confused in this whole sentence 
#if(COMPENSATOR==1||COMPENSATOR==2)

#pragma DATA_SECTION(Cmpns2_Coef, "Cla1ToCpuMsgRAM")
CNTL2P2Z_Coef Cmpns2_Coef;

#pragma DATA_SECTION(Cmpns2, "Cla1ToCpuMsgRAM")
CNTL2P2Z_CLA Cmpns2;

Where does CNTL2P2Z_Coef and CNTL2P2Z_CLA come from ?


I know I am asking a lot but I will really appreciate if you can clarify this two doubts soon. Unfortunately I haven't still been able to run it using your code. I was wondering if these  are what I was missing.

Thanks and Regards,
Sourish


<img width="276" alt="Capture" src="https://user-images.githubusercontent.com/76200580/103931956-1edae580-50ef-11eb-90d2-7652be157509.PNG">

**Comment by fma23** [comment]
my pin assignment in the code I posted may be wrong. You need to make sure the pin assignments matches the control board I bought from TI (https://www.ti.com/tool/BOOSTXL-BUCKCONV)

Your question2: 

I made my defines as below: 

/* takes values: 1,2,3:
 when 1 implements 2P2Z
 when 2: implement PID using bilinear transformation
 when 3: implement PID using backward method */

for example when I use #define  COMPENSATOR     3, it means I am implementing a PID using backward method. All the equations are in the code.

#if(COMPENSATOR==1||COMPENSATOR==2) means if we are implementing a PID  OR 2P2Z. 

also please note that a 2P2Z is just a special case of a PID, that's all.

**Comment by sourishss** [comment]
Hi Farid,

Thanks a lot. I got it running. I have one final question which I would be glad if you can revert back to.

I followed the biricha digital method for 2P2Z coefficients calculation, I guess you mentioned that you followed the same for the code. I was wondering if you followed the Biricha method for coefficients calculation though, since I was able to match the values I am getting with what Biricha is getting, however, I am unable to get your values. Your values seem to working but are very far from what I am getting with biricha's method. How did you come up with your values ?

**Comment by fma23** [comment]
There is an excel sheet in this repo: https://github.com/fma23/Buck-Converter-Peak-Current-Control-Mode-Theory
that's how my 2p2Z coefficients were calculated. 

Note that Bricha codes implements sloop compensation differently. I am using an MCU that supports a built in slope compensation feature. 

Cheers

**Comment by sourishss** [comment]
Hi Farid,

Yes I am following that calculation sheet that you have given. Based on that you have got :
//#define a1_Coef              1.6616
//#define a2_Coef              -0.6616
//#define b0_Coef              2.81
//#define b1_Coef              0.2529   
//#define b2_Coef              -2.5572

However, I saw that the converter does not work with these values. Instead you chose the below values which are not only very far from the values you got after calculation but also in terms of polarity they are opposite in some instances.

//#define a1_Coef              0.8285976581
//#define a2_Coef              0.1714023419
//#define b0_Coef              4.1703226660
//#define b1_Coef              -5.9120992707
//#define b2_Coef              1.9495912223

How did you get these new values ? It is not calculated in your calculation sheet. You have just mentioned these values in one side of the calculation sheet.

Regards,
Sourish

**Comment by sourishss** [comment]
Hi Farid,

Are you planning in the future to post a project on your website using TI microcontrollers for any converter topology ? Just asking since your website was really helpful.

Also, just a quick question tying to the previous discussion with regards to 2P2Z Compensator 
You have written the coefficient values in your code as shown below (no calculation are provided for these values only handwritten in the excel sheet) :
#define a1_Coef              0.8285976581
#define a2_Coef              0.1714023419
#define b0_Coef              4.1703226660
#define b1_Coef              -5.9120992707
#define b2_Coef              1.9495912223 

However, the values that you have calculated for a1,a2,b1,b2 and b0 are quite different in your calculation sheet which are shown below:
#define a1_Coef              1.661612595
#define a2_Coef              -0.661612595
#define b0_Coef              2.810676213
#define b1_Coef              0.252984346
#define b2_Coef             -2.557691867

Can you tell me why is there a difference?  as in some of the values the difference is quite substantial since there are changes in polarity as well.

**Comment by fma23** [comment]
Hi sourish! Sorry for not getting back to you earlier; regarding the coefficient calculation, the values I have are design dependent; I can’t recall how I got them; but you got the correct equations on my excel sheet. 

After that project, I have not done much with TI yet; but if you need my help on any project I can help on a contract basis. 

Please, if there is any knowledge you wanna share with other students, let me know. I can add it to my website and add your name as the author. 

Cheers

**Comment by sourishss** [comment]
Hi Farid,

I am trying to write the Voltage Mode Controller Code using 3P3Z Compensator for the same Buck Converter. Do you think you can help me out if I get stuck somewhere ?

**Comment by fma23** [comment]
Voltage mode control theory is much easier than peak current mode control theory. have a look a this link: https://training.ti.com/c2000-digital-power-supply-workshop

also install the controlsuite for TI C2000. Any questions, I can try to help whenever I have time. However, I found the TI forum to be a great source of help.

Good luck!

**Comment by sourishss** [comment]
Hi,
I am sorry for barging up with questions all the time. Hopefully this will be my last. It is a very small question.

Why have you multiplied Cmpns2.Out with 16 in the line "Comp2Regs.RAMPMAXREF_SHDW=Cmpns2.Out*16; " . I have pasted the whole compensator code below for your reference.

   Cmpns2.Ref=BuckControl_Ref;
    Cmpns2.Fdb=(float) AdcResult.ADCRESULT0;  //Multiply by 1/(2^12) to convert it to per unit float;

    //CNTL2P2Z_CLA(Cmpns2, Cmpns2_Coef);

   /* Compute the error */
   Cmpns2.Errn=Cmpns2.Ref-Cmpns2.Fdb;
   // PreSat = e(n-2)*B2 + e(n-1)*B1 + e(n)*B0 + u(n-2)*A2 + u(n-1)*A1
   Cmpns2.OutPreSat = Cmpns2_Coef.b2*Cmpns2.Errn2 +Cmpns2_Coef.b1*Cmpns2.Errn1 + Cmpns2_Coef.b0*Cmpns2.Errn + Cmpns2_Coef.a2*Cmpns2.Out2 + Cmpns2_Coef.a1*Cmpns2.Out1;
   /* store history of error*/
   Cmpns2.Errn2 = Cmpns2.Errn1;
   Cmpns2.Errn1 = Cmpns2.Errn;
   Cmpns2.Out=Cmpns2.OutPreSat;
   /*  Saturate the output, use intrinsic for the CLA compiler */
   Cmpns2.Out=__mminf32(Cmpns2.Out,Cmpns2_Coef.OutMax);
   Cmpns2.Out=__mmaxf32(Cmpns2.Out,Cmpns2_Coef.OutMin);
   /* store the history of outputs */
   Cmpns2.Out2 = Cmpns2.Out1;
   Cmpns2.Out1 = Cmpns2.Out;

   MEALLOW;
   //Comp2Regs.DACVAL.all = Cmpns2.Out*1023; //Multiply by 2^6, because this is Q10
   Comp2Regs.RAMPMAXREF_SHDW=Cmpns2.Out*16;  //Cmpns1.Out*2^10*2^6;

**Comment by fma23** [comment]
I want to close communication on github. Can you please repost this question on the webpage so that others may benefit as well?

But here is the answer your question: the output value of the PID or 2P2Z is a scaled value of: 1/2^12 ( because the ADC used is 12 bits ). The slope ramp down starting from the PID or the 2P2Z output value.

RAMPMAXREF_SHDW value needs to be scaled by 2^16 ( based on the datasheet, you can look it up.)
Thus:  Comp2Regs.RAMPMAXREF_SHDW=pid output( scaled by 1/2^12) *10^16=pid output*2^4.
